<%-- 
    Document   : home.jsp
    Created on : 8 juin 2020, 16:44:38
    Author     : stagjava
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Home Page</title>
    </head>
    <body>
        <h1>Hello World!</h1>
        <p>This is the Home JSP page generated by HomeServlet</p>
            
    </body>
</html>
